# Generated by Django 3.1.2 on 2021-01-04 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('policy_type', models.IntegerField(choices=[(0, 'jan_dhan_yojna'), (1, 'jivan_bima'), (2, 'jivan_laabh')])),
                ('policy_number', models.CharField(max_length=10, unique=True)),
                ('premium', models.IntegerField()),
                ('sum_assured', models.IntegerField()),
                ('year_of_policy', models.IntegerField()),
                ('beneficiary_name', models.CharField(max_length=50)),
                ('created_on', models.DateField()),
                ('renew_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Deactive'), (1, 'Active')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
