# Generated by Django 3.1.2 on 2021-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lic',
            old_name='address',
            new_name='address_line_one',
        ),
        migrations.AddField(
            model_name='lic',
            name='address_line_two',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lic',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lic',
            name='lendmark',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='lic',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
