# Generated by Django 3.1.6 on 2021-03-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_no',
            field=models.CharField(max_length=12),
        ),
    ]
