# Generated by Django 3.1.2 on 2021-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210104_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='lic',
            name='pay_for',
            field=models.IntegerField(choices=[('quarterly', 'Quarterly'), ('six_month', 'Six Month'), ('yearly', 'Yearly')], default=1),
            preserve_default=False,
        ),
    ]
