# Generated by Django 3.1.6 on 2021-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210308_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='contact_no',
            field=models.IntegerField(),
        ),
    ]
