# Generated by Django 3.1.2 on 2021-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_lic_pay_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='pay_for',
            field=models.CharField(choices=[('quarterly', 'Quarterly'), ('six_month', 'Six Month'), ('yearly', 'Yearly')], max_length=50),
        ),
    ]
