# Generated by Django 3.1.2 on 2021-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210203_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
