# Generated by Django 3.1.6 on 2021-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210308_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='created_on',
            field=models.DateTimeField(max_length=50),
        ),
    ]
