# Generated by Django 3.1.2 on 2021-01-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210104_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='policy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PolicyType', to='dashboard.policytype'),
        ),
    ]
