# Generated by Django 3.1.2 on 2021-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210203_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='inquiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='inquiry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
