# Generated by Django 3.1.2 on 2021-01-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210104_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lic',
            name='user',
        ),
    ]
