# Generated by Django 3.1.2 on 2021-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210203_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='inquiry_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
