# Generated by Django 3.1.6 on 2021-03-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210313_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='family_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
