# Generated by Django 3.1.6 on 2021-03-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210317_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='family_name',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
