# Generated by Django 3.1.2 on 2021-02-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210203_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('News Paper', 'News Paper'), ('Magazine', 'Magazine'), ('Advertising', 'Advertising'), ('Google', 'Google'), ('Gmail', 'Gmail'), ('Friends Reference', 'Friends Reference')], max_length=50),
        ),
    ]
