# Generated by Django 3.1.2 on 2021-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210203_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='inquiry_date',
            field=models.CharField(max_length=50),
        ),
    ]
