# Generated by Django 3.1.6 on 2021-03-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210317_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lic',
            old_name='family_name',
            new_name='experience',
        ),
        migrations.RemoveField(
            model_name='lic',
            name='family_dob',
        ),
        migrations.RemoveField(
            model_name='lic',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lic',
            name='relation_type',
        ),
        migrations.AddField(
            model_name='lic',
            name='position',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lic',
            name='skill',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
