# Generated by Django 3.1.2 on 2021-02-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210204_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='inquiry_time',
            field=models.CharField(max_length=50),
        ),
    ]
