# Generated by Django 3.1.6 on 2021-03-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210317_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lic',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='lic',
            name='position',
        ),
        migrations.RemoveField(
            model_name='lic',
            name='skill',
        ),
    ]
