# Generated by Django 3.1.6 on 2021-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210325_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='created_on',
            field=models.DateField(max_length=50),
        ),
    ]
