# Generated by Django 3.1.6 on 2021-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210325_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='created_on',
            field=models.CharField(max_length=50),
        ),
    ]
