# Generated by Django 3.1.2 on 2021-01-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_lic_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='created_on',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lic',
            name='dob',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lic',
            name='renew_date',
            field=models.CharField(max_length=20),
        ),
    ]
