# Generated by Django 3.1.2 on 2021-02-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210204_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(),
        ),
    ]
