# Generated by Django 3.1.2 on 2021-02-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210204_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('News_Paper', 'News_Paper'), ('Magazine', 'Magazine'), ('Advertising', 'Advertising'), ('Google', 'Google'), ('Gmail', 'Gmail'), ('Friends_Reference', 'Friends_Reference')], max_length=50),
        ),
    ]
