# Generated by Django 3.1.2 on 2021-02-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210205_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
