# Generated by Django 3.1.2 on 2021-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210107_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
