# Generated by Django 3.1.2 on 2021-01-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210107_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='file_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lic',
            name='contact',
            field=models.CharField(max_length=50),
        ),
    ]
