# Generated by Django 3.1.5 on 2021-01-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210108_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='lic',
            name='middle_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
