# Generated by Django 3.1.2 on 2021-02-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_discuss_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.discuss'),
        ),
    ]
