# Generated by Django 3.1.5 on 2021-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_lic_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lic',
            name='pay_for',
            field=models.CharField(choices=[('Annually', 'Annually'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('HalfYear', 'HalfYear')], max_length=50),
        ),
        migrations.AlterField(
            model_name='policytype',
            name='policy_type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
