# Generated by Django 3.1.2 on 2021-02-08 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210208_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AddField(
            model_name='discuss',
            name='full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discuss',
            name='massage',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
