# Generated by Django 3.1.2 on 2021-02-08 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210208_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='discuss',
            name='massage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
        ),
    ]
