# Generated by Django 3.1.2 on 2021-02-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20210208_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='discuss',
            name='lead',
            field=models.ManyToManyField(to='dashboard.Lead'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='massage',
            field=models.CharField(max_length=1000),
        ),
    ]
