# Generated by Django 3.1.2 on 2021-02-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210208_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.ManyToManyField(to='dashboard.discuss'),
        ),
    ]
