# Generated by Django 3.1.2 on 2021-02-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20210208_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='massage',
            new_name='message',
        ),
    ]
