# Generated by Django 3.1.2 on 2021-02-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20210208_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
    ]
