# Generated by Django 3.1.2 on 2021-02-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_lead_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='message',
        ),
        migrations.AddField(
            model_name='discuss',
            name='msg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.lead'),
            preserve_default=False,
        ),
    ]
