# Generated by Django 3.1.2 on 2021-02-12 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0031_auto_20210210_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mutual_Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('contact_no', models.CharField(max_length=30)),
                ('address_line_one', models.CharField(max_length=30)),
                ('address_line_two', models.CharField(max_length=30)),
                ('lendmark', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], max_length=50)),
                ('statement_date', models.CharField(max_length=30)),
                ('folio_no', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(choices=[('APOLLO MUNICH GIC LTD', 'APOLLO MUNICH GIC LTD'), ('Bajaj', 'Bajaj'), ('BAJAJ ALLINZ GIC LTD', 'BAJAJ ALLINZ GIC LTD'), ('BHARTI AXA GIC LTD', 'BHARTI AXA GIC LTD'), ('FUTURE GENERALLY GIC LTD', 'FUTURE GENERALLY GIC LTD'), ('GO-DIGIT GIC LTD', 'GO-DIGIT GIC LTD'), ('hdfc bank', 'hdfc bank'), ('HDFC ERGO GIC LTD', 'HDFC ERGO GIC LTD'), ('HDFC Life', 'HDFC Life'), ('ICICI LOMBARD GIC LTD', 'ICICI LOMBARD GIC LTD'), ('Iffco Tokio', 'Iffco Tokio'), ('IFFCO TOKIO GIC LTD', 'IFFCO TOKIO GIC LTD'), ('Kotak Life Insurance Company', 'Kotak Life Insurance Company'), ('LIBERTY INSURANCE CO LTD', 'LIBERTY INSURANCE CO LTD'), ('LIC', 'LIC'), ('LIC OF INDIA', 'LIC OF INDIA'), ('Life', 'Life'), ('Life insurance corporation of india', 'Life insurance corporation of india'), ('Max Bhupa', 'Max Bhupa')], max_length=50)),
                ('name_holder', models.CharField(max_length=30)),
                ('tax_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50)),
                ('mode_of_holding', models.CharField(choices=[('Single', 'Single'), ('Family', 'Family')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
