# Generated by Django 3.1.2 on 2021-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_mutual_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual_fund',
            name='account_no',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutual_fund',
            name='bank_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutual_fund',
            name='ifsc_code',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
