# Generated by Django 3.1.6 on 2021-02-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20210212_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual_fund',
            name='created_on',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutual_fund',
            name='pay_for',
            field=models.CharField(choices=[('Annually', 'Annually'), ('Quarterly', 'Quarterly'), ('Monthly', 'Monthly'), ('HalfYear', 'HalfYear'), ('OneTime', 'OneTime')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutual_fund',
            name='premium',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutual_fund',
            name='renew_date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
