# Generated by Django 3.1.6 on 2021-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20210213_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual_fund',
            name='status',
            field=models.IntegerField(choices=[(0, 'Deactive'), (1, 'Active')], default=1),
        ),
    ]
