# Generated by Django 3.1.6 on 2021-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_mutual_fund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lic',
            name='commission',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lic',
            name='commission_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
