# Generated by Django 3.1.6 on 2021-02-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20210223_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutual_fund',
            name='commission',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mutual_fund',
            name='commission_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
